### ISSUE TITLE
一直显示正在连接

### ISSUE THREAD

**Issue by Skye-X** [MaaAssistantArknights/MeoAsstElectronUI#198]
### 问题描述

输入adb地址后一直显示正在连接，输入两个就会有两个正在连接一起转，maa可以正常连,重装过一次，目前试了beta12和13都是这样。

### 日志文件

[Maa App-20230830.log](https://github.com/MaaAssistantArknights/MaaX/files/12474298/Maa.App-20230830.log)

### 截图

![屏幕截图 2023-08-30 174957](https://github.com/MaaAssistantArknights/MaaX/assets/20748609/bac28fbd-c32c-4a6b-89db-b60424a347a7)

### 还有别的吗？

模拟器是mumu12，wsa也试了连不上。maa都可以正常连。

**Comment by ChingCdesu** [comment]
你可以试试左边的刷新按钮，他会自动检测你开着的模拟器，但需要用管理员身份打开

**Comment by Skye-X** [comment]
> 你可以试试左边的刷新按钮，他会自动检测你开着的模拟器，但需要用管理员身份打开

这样确实可以欸！不过每次都管理员打开好麻烦呀（

**Comment by Skye-X** [comment]
> 
不过我觉得应该是adb的问题，连上之后任务执行不了。啥时候可以跟maa一样直接在软件里开换adb目录就好了

**Comment by bakashigure** [comment]
看日志确实是adb出了差错, 方便截一下这个路径里的内容吗 `%appdata%/maa-x/platform-tools`

**Comment by ChingCdesu** [comment]
> > 你可以试试左边的刷新按钮，他会自动检测你开着的模拟器，但需要用管理员身份打开
> 
> 这样确实可以欸！不过每次都管理员打开好麻烦呀（

可以右键点exe的属性，然后在里面把用管理员权限打开打勾，这样双击也是管理员打开了
我们还在探究怎么装的时候就是管理员打开
