### ISSUE TITLE
目录空：packages\common\ArknightsGameData

### ISSUE THREAD

**Issue by kevin2y** [MaaAssistantArknights/MeoAsstElectronUI#199]
### 问题描述

maax一直显示loading..

查console，提示找不到一个文件

GET http://127.0.0.1:3344/@id/D:/games/MaaX/packages/common/ArknightsGameData/zh_CN/gamedata/excel/item_table.json?import net::ERR_ABORTED 404 (Not Found)

### 截图

![image](https://github.com/MaaAssistantArknights/MaaX/assets/1572928/5d157b40-21ea-4564-83eb-09a38f7571ca)

**Comment by kevin2y** [comment]
原来ArknightsGameData需要另外git
进入该目录， git clone https://github.com/Kengxxiao/ArknightsGameData.git

**Comment by ChingCdesu** [comment]
执行一次`git submodule update --init`等同于你后面的`git clone`
