### ISSUE TITLE
maax初始化下载安装maa核心组件失败

### ISSUE THREAD

**Issue by Flame38** [MaaAssistantArknights/MeoAsstElectronUI#209]
### 问题描述

解压maax压缩包后启动maax初始化安装，core组件下载卡0%，换成国内镜像后安装失败

### 日志文件

[Maa App-20231223.log](https://github.com/MaaAssistantArknights/MaaX/files/13757992/Maa.App-20231223.log)

### 截图

![9W59RKXC5TRY`{Z_V7SRHDL](https://github.com/MaaAssistantArknights/MaaX/assets/55654498/c770c823-eff8-40bc-906f-d3f8925ca446)

**Comment by keymao** [comment]
这个是程序内匹配链接的逻辑有bug，导致的匹配失败，不清楚项目组还维护不维护  我就不commit了  反正是这个问题。
