### ISSUE TITLE
界面上没有关闭按钮;信用购买中图片加载失败

### ISSUE THREAD

**Issue by whitecodes** [MaaAssistantArknights/MeoAsstElectronUI#217]
### 问题描述

MAA-X 可以运行，但是界面上没有关闭按钮，只能通过任务栏关闭：

管理购买选项中，大部分图片都加载失败了

### 日志文件

[Maa App-20240517.log](https://github.com/MaaAssistantArknights/MaaX/files/15351610/Maa.App-20240517.log)

### 截图

![Screenshot_20240517_225800](https://github.com/MaaAssistantArknights/MaaX/assets/8749745/8199450d-7555-4d45-80e0-23850996431e)

### 还有别的吗？

[osversion.txt](https://github.com/MaaAssistantArknights/MaaX/files/15351645/osversion.txt)

**Comment by ChingCdesu** [comment]
### 该项目可能缺少维护
按esc或者点击弹出框以外的部分即可关闭
新版的图片api还没有和prts.wiki对接

**Comment by whitecodes** [comment]
主界面也没有关闭按钮

**Comment by whitecodes** [comment]
图片链接的修改发了pr，看下没有问题的话，麻烦出个版本

**Comment by whitecodes** [comment]
修好了

**Comment by bakashigure** [comment]
这是啥os

**Comment by whitecodes** [comment]
[Arch Linux x86_64](https://archlinux.org/)

图形环境是 KDE Plasma 6，屏幕下面的是任务栏，手动设置了可变宽度，显示的内容是手动设置的
